import type { Metadata } from "next";
import {
  Corben,
  Cormorant_Garamond,
  Geist,
  Geist_Mono,
  Metamorphous,
  Montaga,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Cursor from "@/components/ui/cursor";
import Navbar from "@/components/Navbar/Navbar";

const corben = Cormorant_Garamond({
  variable: "--font-corben",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${corben.variable} ${montserrat.variable} antialiased max-w-screen overflow-x-hidden`}>
        <Navbar></Navbar>
        {children}
        <Toaster richColors />
        <Cursor></Cursor>
      </body>
    </html>
  );
}
